### ISSUE TITLE
Unable to run the Shared Storage Demo locally 

### ISSUE THREAD

**Issue by sanjalijha** [GoogleChromeLabs/shared-storage-demo#26]
Hi, I work in the Google Ad Traffic Quality Team. I followed the steps for the 'Local Development' of the Shared Storage Demo. I am unable to run it locally and keep running into '502 Bad Gateway nginx/1.23.4' error on the Publisher Pages and the aggregatable reports do not get generated. I've attached the console output and the error page - is there something I am doing wrong?

![image](https://github.com/GoogleChromeLabs/shared-storage-demo/assets/47723261/2101567c-5964-4afb-af25-92c479950a75)
![image](https://github.com/GoogleChromeLabs/shared-storage-demo/assets/47723261/41aa9f76-6bd9-48c9-96ee-4ce15399bb07)

**Comment by kevinkiklee** [comment]
Hi there.  The README contains the line `proxy_pass http://localhost:8087/` where it tries to proxies port 4337 to 8087.  That line is no longer correct and `8087` should be updated to `3007`. 

A couple of months ago, I changed the port from 8080 to 3000 to integrate it with another app that was running on 8080 locally.  I forgot to update the README afterwards.  I apologize for the trouble you went through.
